### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by milkina** [SvitlanaBg/JHW#1]
1. Добавьте перегруженный метод receiveCall, который принимает два параметра - имя звонящего и номер телефона звонящего. Вызвать этот метод.
2.Переменные класса рекомендуется делать private.
3.Доступ к переменным класса осуществляется через геттеры и сеттеры. 
4.Методы и конструкторы должны быть с модификаторами доступа.
5. В классе рекомендуется сначала объявляются статические переменные, переменные класса, потом конструкторы, геттеры, сеттеры. Потом все остальные методы.
6. Желательно переопределять в создаваемом классе методы toString, equals и hashCode.

**Comment by milkina** [comment]
1.Комментарий ненужный убрать.
2. Создать объект(ы) этого класса и вызвать их методы.

**Comment by milkina** [comment]
Пишу еще раз:
1. Добавьте перегруженный метод receiveCall, который принимает два параметра - имя звонящего и номер телефона звонящего. Вызвать этот метод.
2. Переменные класса рекомендуется делать private.
3. Доступ к переменным класса осуществляется через геттеры и сеттеры.
4. Методы и конструкторы должны быть с модификаторами доступа.
5. В классе рекомендуется сначала объявляются статические переменные, переменные класса, потом конструкторы, геттеры, сеттеры. Потом все остальные методы.
6. Желательно переопределять в создаваемом классе методы toString, equals и hashCode.

**Comment by milkina** [comment]
Done, но - Для одного конструктора не дописала мод. доступа.

**Comment by SvitlanaBg** [comment]
Дописала модификаторы досткпа для конструкторов
