### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by milkina** [SvitlanaBg/JHW#13]
1. Убрать ненужный импорт.
2.  В метод matrixMultiply  передавай только int a. Используй this. Выводить на консоль не надо - вывод на консоль в методе print. Метод пусть возвращает или третью матрицу или записывай результат в текущую.
3.  В matrixSum тоже самое - передавай только одну матрицу, склавдывай ее с текущей. Метод пусть возвращает или третью матрицу или записывай результат в текущую. Выводить на консоль не надо.

**Comment by SvitlanaBg** [comment]
Исправила.
