### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by milkina** [SvitlanaBg/JHW#14]
1. Добавить мод. доступа методу recurs.
2. Блок оператора if рекомендуется писать в фиг. скобках.
3. Вместо
```
 result =
                recurs(a, b);
```
лучше 
` result = recurs(a, b);`
4. Вместо
`  if (a < b) {
            System.out.print(a + " ");
            a++;
        }`
можно 
`  if (a < b) {
            System.out.print(a++ + " ");
        }`

**Comment by SvitlanaBg** [comment]
Добавила модификаторы доступа и переписала остальное.

**Comment by milkina** [comment]
пункт 2 не выполнен

**Comment by SvitlanaBg** [comment]
Добавила фигурные скобки в блок оператора if
